# Run from inside the sophiabertolino.com folder:  .\download-assets.ps1
$ErrorActionPreference = "Continue"
New-Item -ItemType Directory -Force -Path "assets\gallery" | Out-Null
New-Item -ItemType Directory -Force -Path "assets\files"   | Out-Null
$items = @(
  @{u="https://sophiabertolino.com/wp-content/uploads/2025/12/Sophia_Gallery_08.jpg"; f="assets\gallery\Sophia_Gallery_08.jpg"},
  @{u="https://sophiabertolino.com/wp-content/uploads/2025/12/Sophia_Gallery_07.jpg"; f="assets\gallery\Sophia_Gallery_07.jpg"},
  @{u="https://sophiabertolino.com/wp-content/uploads/2025/12/Sophia_Gallery_09.jpg"; f="assets\gallery\Sophia_Gallery_09.jpg"},
  @{u="https://sophiabertolino.com/wp-content/uploads/2025/12/Sophia_Gallery_37.jpg"; f="assets\gallery\Sophia_Gallery_37.jpg"},
  @{u="https://sophiabertolino.com/wp-content/uploads/2025/12/Sophia_Gallery_39.jpg"; f="assets\gallery\Sophia_Gallery_39.jpg"},
  @{u="https://sophiabertolino.com/wp-content/uploads/2025/12/Sophia_Gallery_28.jpg"; f="assets\gallery\Sophia_Gallery_28.jpg"},
  @{u="https://sophiabertolino.com/wp-content/uploads/2025/12/Sophia_Gallery_34.jpg"; f="assets\gallery\Sophia_Gallery_34.jpg"},
  @{u="https://sophiabertolino.com/wp-content/uploads/2025/12/Sophia_Gallery_33.jpg"; f="assets\gallery\Sophia_Gallery_33.jpg"},
  @{u="https://sophiabertolino.com/wp-content/uploads/2025/12/Sophia_Gallery_23.jpg"; f="assets\gallery\Sophia_Gallery_23.jpg"},
  @{u="https://sophiabertolino.com/wp-content/uploads/2025/12/Sophia_Gallery_21.jpg"; f="assets\gallery\Sophia_Gallery_21.jpg"},
  @{u="https://sophiabertolino.com/wp-content/uploads/2025/12/Sophia_Gallery_20.jpg"; f="assets\gallery\Sophia_Gallery_20.jpg"},
  @{u="https://sophiabertolino.com/wp-content/uploads/2025/12/Sophia_Gallery_04.jpg"; f="assets\gallery\Sophia_Gallery_04.jpg"},
  @{u="https://sophiabertolino.com/wp-content/uploads/2025/12/Sophia_Gallery_11.jpg"; f="assets\gallery\Sophia_Gallery_11.jpg"},
  @{u="https://sophiabertolino.com/wp-content/uploads/2025/12/Sophia_Gallery_12.jpg"; f="assets\gallery\Sophia_Gallery_12.jpg"},
  @{u="https://sophiabertolino.com/wp-content/uploads/2025/12/Sophia_Gallery_16.jpg"; f="assets\gallery\Sophia_Gallery_16.jpg"},
  @{u="https://sophiabertolino.com/wp-content/uploads/2025/12/Sophia_Gallery_14.jpg"; f="assets\gallery\Sophia_Gallery_14.jpg"},
  @{u="https://sophiabertolino.com/wp-content/uploads/2025/12/Sophia_Gallery_06.jpg"; f="assets\gallery\Sophia_Gallery_06.jpg"},
  @{u="https://sophiabertolino.com/wp-content/uploads/2025/12/Sophia_Gallery_05.jpg"; f="assets\gallery\Sophia_Gallery_05.jpg"},
  @{u="https://sophiabertolino.com/wp-content/uploads/2026/01/Sophia_pic_3.jpg"; f="assets\gallery\Sophia_pic_3.jpg"},
  @{u="https://sophiabertolino.com/wp-content/uploads/2026/01/IMG_4213.jpeg"; f="assets\gallery\IMG_4213.jpeg"},
  @{u="https://sophiabertolino.com/wp-content/uploads/2026/01/IMG_4094.jpeg"; f="assets\gallery\IMG_4094.jpeg"},
  @{u="https://sophiabertolino.com/wp-content/uploads/2026/01/IMG_4087.jpeg"; f="assets\gallery\IMG_4087.jpeg"},
  @{u="https://sophiabertolino.com/wp-content/uploads/2026/01/Sophia_pic_2.jpg"; f="assets\gallery\Sophia_pic_2.jpg"},
  @{u="https://sophiabertolino.com/wp-content/uploads/2026/01/IMG_4184.jpeg"; f="assets\gallery\IMG_4184.jpeg"},
  @{u="https://sophiabertolino.com/wp-content/uploads/2026/01/IMG_4114.jpeg"; f="assets\gallery\IMG_4114.jpeg"},
  @{u="https://sophiabertolino.com/wp-content/uploads/2026/01/IMG_4223.jpeg"; f="assets\gallery\IMG_4223.jpeg"},
  @{u="https://sophiabertolino.com/wp-content/uploads/2026/01/IMG_4232-2.jpeg"; f="assets\gallery\IMG_4232-2.jpeg"},
  @{u="https://sophiabertolino.com/wp-content/uploads/2026/01/IMG_4220.jpeg"; f="assets\gallery\IMG_4220.jpeg"},
  @{u="https://sophiabertolino.com/wp-content/uploads/2026/01/IMG_7983.jpeg"; f="assets\gallery\IMG_7983.jpeg"},
  @{u="https://sophiabertolino.com/wp-content/uploads/2026/01/IMG_7973.jpeg"; f="assets\gallery\IMG_7973.jpeg"},
  @{u="https://sophiabertolino.com/wp-content/uploads/2026/01/IMG_8351.jpeg"; f="assets\gallery\IMG_8351.jpeg"},
  @{u="https://sophiabertolino.com/wp-content/uploads/2026/01/IMG_7967.jpeg"; f="assets\gallery\IMG_7967.jpeg"},
  @{u="https://sophiabertolino.com/wp-content/uploads/2026/01/IMG_8359.jpeg"; f="assets\gallery\IMG_8359.jpeg"},
  @{u="https://sophiabertolino.com/wp-content/uploads/2026/01/IMG_8367.jpeg"; f="assets\gallery\IMG_8367.jpeg"},
  @{u="https://sophiabertolino.com/wp-content/uploads/2026/01/IMG_8373.jpeg"; f="assets\gallery\IMG_8373.jpeg"},
  @{u="https://sophiabertolino.com/wp-content/uploads/2026/01/IMG_8361.jpeg"; f="assets\gallery\IMG_8361.jpeg"},
  @{u="https://sophiabertolino.com/wp-content/uploads/2026/01/IMG_8365.jpeg"; f="assets\gallery\IMG_8365.jpeg"},
  @{u="https://sophiabertolino.com/wp-content/uploads/2026/01/IMG_8380.jpeg"; f="assets\gallery\IMG_8380.jpeg"},
  @{u="https://sophiabertolino.com/wp-content/uploads/2026/01/IMG_7931.jpeg"; f="assets\gallery\IMG_7931.jpeg"},
  @{u="https://sophiabertolino.com/wp-content/uploads/2026/01/IMG_7924.jpeg"; f="assets\gallery\IMG_7924.jpeg"},
  @{u="https://sophiabertolino.com/wp-content/uploads/2026/01/IMG_7952.jpeg"; f="assets\gallery\IMG_7952.jpeg"},
  @{u="https://sophiabertolino.com/wp-content/uploads/2026/01/IMG_7901.jpeg"; f="assets\gallery\IMG_7901.jpeg"},
  @{u="https://sophiabertolino.com/wp-content/uploads/2026/01/IMG_7893.jpeg"; f="assets\gallery\IMG_7893.jpeg"},
  @{u="https://sophiabertolino.com/wp-content/uploads/2026/01/IMG_7953.jpeg"; f="assets\gallery\IMG_7953.jpeg"},
  @{u="https://sophiabertolino.com/wp-content/uploads/2026/01/IMG_0468.jpeg"; f="assets\gallery\IMG_0468.jpeg"},
  @{u="https://sophiabertolino.com/wp-content/uploads/2026/01/IMG_0477.jpeg"; f="assets\gallery\IMG_0477.jpeg"},
  @{u="https://sophiabertolino.com/wp-content/uploads/2026/01/IMG_0464.jpeg"; f="assets\gallery\IMG_0464.jpeg"},
  @{u="https://sophiabertolino.com/wp-content/uploads/2026/01/IMG_0475.jpeg"; f="assets\gallery\IMG_0475.jpeg"},
  @{u="https://sophiabertolino.com/wp-content/uploads/2026/01/IMG_0450.jpeg"; f="assets\gallery\IMG_0450.jpeg"},
  @{u="https://sophiabertolino.com/wp-content/uploads/2026/01/IMG_0425.jpeg"; f="assets\gallery\IMG_0425.jpeg"},
  @{u="https://sophiabertolino.com/wp-content/uploads/2026/01/IMG_0456.jpeg"; f="assets\gallery\IMG_0456.jpeg"},
  @{u="https://sophiabertolino.com/wp-content/uploads/2026/01/IMG_0424.jpeg"; f="assets\gallery\IMG_0424.jpeg"},
  @{u="https://sophiabertolino.com/wp-content/uploads/2026/01/IMG_0463.jpeg"; f="assets\gallery\IMG_0463.jpeg"},
  @{u="https://sophiabertolino.com/wp-content/uploads/2026/01/IMG_6824.jpeg"; f="assets\gallery\IMG_6824.jpeg"},
  @{u="https://sophiabertolino.com/wp-content/uploads/2026/01/IMG_6816.jpeg"; f="assets\gallery\IMG_6816.jpeg"},
  @{u="https://sophiabertolino.com/wp-content/uploads/2026/01/IMG_6830.jpeg"; f="assets\gallery\IMG_6830.jpeg"},
  @{u="https://sophiabertolino.com/wp-content/uploads/2026/01/IMG_6825.jpeg"; f="assets\gallery\IMG_6825.jpeg"},
  @{u="https://sophiabertolino.com/wp-content/uploads/2026/01/IMG_6827.jpeg"; f="assets\gallery\IMG_6827.jpeg"},
  @{u="https://sophiabertolino.com/wp-content/uploads/2026/01/IMG_6826.jpeg"; f="assets\gallery\IMG_6826.jpeg"},
  @{u="https://sophiabertolino.com/wp-content/uploads/2026/01/IMG_6821.jpeg"; f="assets\gallery\IMG_6821.jpeg"},
  @{u="https://sophiabertolino.com/wp-content/uploads/2026/01/IMG_6822.jpeg"; f="assets\gallery\IMG_6822.jpeg"},
  @{u="https://sophiabertolino.com/wp-content/uploads/2026/01/IMG_6819.jpeg"; f="assets\gallery\IMG_6819.jpeg"},
  @{u="https://sophiabertolino.com/wp-content/uploads/2026/03/Sophia_Bertolino_performance_resume-2.pdf"; f="assets\files\Sophia_Bertolino_Resume.pdf"}
)
$ok=0; $fail=0
foreach ($i in $items) {
  try { Invoke-WebRequest -Uri $i.u -OutFile $i.f -UseBasicParsing; Write-Host "OK   $($i.f)"; $ok++ }
  catch { Write-Host "FAIL $($i.u)" -ForegroundColor Red; $fail++ }
}
Write-Host ""; Write-Host "Done. $ok downloaded, $fail failed."
